run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
